// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using doKolosa2.DAL;

#nullable disable

namespace doKolosa2.Migrations
{
    [DbContext(typeof(GakkoDbContext))]
    partial class GakkoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("doKolosa2.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<int>("IdStudentGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdStudentGroup");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            IdStudent = 1,
                            IdStudentGroup = 1,
                            Name = "Karolina"
                        });
                });

            modelBuilder.Entity("doKolosa2.Models.StudentGroup", b =>
                {
                    b.Property<int>("IdStudentGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudentGroup"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStudentGroup");

                    b.ToTable("StudentGroups");

                    b.HasData(
                        new
                        {
                            IdStudentGroup = 1,
                            Name = "GrupaAng"
                        });
                });

            modelBuilder.Entity("doKolosa2.Models.Student", b =>
                {
                    b.HasOne("doKolosa2.Models.StudentGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("IdStudentGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("doKolosa2.Models.StudentGroup", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
